config/routes.rb
Rails.application.routes.draw do
  get 'items/index'
  get 'items/show'
  get 'items/new'
  get 'items/edit'
  root  'departments#index'
  resources :departments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
 belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    set_department

    if @department.update(department_params)
      redirect_to departments_path
    else
      render :edit
    end
  end

  def destroy
    set_department.destroy
    redirect_to departments_path
  end


  private
    def set_department
       @department = Department.find(params[:id])
    end

    def department_params
       params.require(:department).permit(:name)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  def index
    @items = @department.items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    #@item = @department.items.new
    @item = Item.new(department_id: params[:department_id])
    render partial: "form"
  end

  def edit
    @item = Item.find(params[:id])
    render partial: "form"
  end

  def create
    @item = @department.items.new(items_params)

    if @item.save
      redirect_to [@department, @item]
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    if (@item.update(item_params))
      redirect_to department_path(@department, @item)
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to department_path
  end

  private

  def set_department
    @department = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<%= form_for @department do |f| %>
<%= f.label :name %>
<%= f.text_field :name, autofocus: true %><br />
<%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1><font size = +16>Edit Department</font></h1>
<h4>Please fill out the new name for the department.</h4><hr />

<%= render partial: "form"%>

app/views/departments/index.html.erb
<h1><font size = +16>All Departments</font></h1>
<h4>Click on the department to see items in that department</h4>
<p><%= link_to "Create A New Department", new_department_path %><hr />

<% @departments.each do |department| %>
    <h2><%= department.name %><br />
    <font size = -1><%= link_to "View",  department_path(department) %></font>
    <font size = -1><%= link_to "Edit", edit_department_path(department) %></font>
    <font size = -1><%= link_to "Delete", department_path(department), method: :delete%>
<% end %>

app/views/departments/new.html.erb
<h1><font size = +16>Create a New Department</font></h1><hr />

<%= render partial: "form" %>

app/views/departments/show.html.erb
<h1><font size = +16><%= @department.name %></font></h1>
<%= link_to "Create a new item?",  items_new_path(@department) %>
<h2> <%= "All Items in #{@department.name}:" %></h2>

app/views/items/_form.html.erb
<%= form_for [@department, @item] do |f| %>
<%= f.label :name %>
<%= f.text_field :name, autofocus: true %><br />
<%# <% hidden_field_tag :department_id, @department.id %>
<%# <% item.department_id = params[:department_id]%>
<%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items#index</h1>
<p>Find me in app/views/items/index.html.erb</p>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>